###############################################################################
#
# Andrea Estrada | arestrad
# 112 F17 TP
# Text descriptions for print out between levels
# 
###############################################################################

levelOne = ["game objective: collect more points than your opponent", None, None, 
	"general gameplay:", "-each level will introduce new powerups and features",
	"-each level's gameboard is a maze generated by a different randomizing algorithm",
	"-levels are over when timer is up", None, None, "level one:", 
	"-in level one, capture as many points (yellow collectables) as possible",
	"-you will navigate through a maze generated by a binary algorithm",
	"-use arrow keys to navigate"
	"-to adjust speed of your player:", "       -press \'a\' to decrease speed", 
	"       -press \'s\' to increase speed"]

levelTwo = ["next up: explore a recursive division maze, collect point", "piles to get multiple points in one go, and avoid monsters"]

levelThree = ["next up: navigate a sidewinder maze, collect and shoot", "ammo (spacebar to shoot... your player will automatically", "aim at your opponent!)"]

levelFour = ["next up: go through an eller's maze, and collect powerups that let you", "pause the mosnters, gain triple points, and go through walls.", "you can have one powerup at a time."]

levelFive = ["last chance! explore a hunt and kill maze and gather any last", "minute points. careful, the maze is getting more complex!"]
